# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: abe74f405f3e1d9ba074736c401537fe6827a92101ffa9074fd951fdefa40f8556ee4cf31fde1f965792f70c1f0321169c8c9ced49630c0dd9071f9f76bcec74

test:
  secret_key_base: 7a62812a8b2297b44749c3e1d0345568b91e6f2c96cdafec92f66e49718a856972069710d01cb0b1337d44fd5e228d11e888ba42603c107ca5c0283b0da618d4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
